### ISSUE TITLE
Convert  eyevinntechnology/2dash docker image to automated build

### ISSUE THREAD

**Issue by tecfu** [Eyevinn/docker-2dash#1]
Issue:

The docker image your script uses isn't built with a Dockerfile hosted on Github. Would you have any objection to linking https://hub.docker.com/r/eyevinntechnology/2dash/ to its Dockerfile? 

See below:

https://github.com/Eyevinn/docker-2dash/blob/eeae1061d12e8fc0499dd26db88a97a47bdd2c6d/build-docker.sh#L10

Many thanks for your *very* underrated public contributions.

**Comment by birme** [comment]
Thank you for the report.

The Dockerfile that this image is built from is actually available in this repository but I assume you are asking for the Dockerfile for the eyevinntechnology/packager-base image. Am I correct?

**Comment by tecfu** [comment]
I apologize for being completely incorrect about what I was asking for. Thanks for your patience. 

Yes, I'm looking for the Dockerfile you used to build [eyevinntechnology/packager-base](https://hub.docker.com/r/eyevinntechnology/packager-base/). For 2 reasons: 

[1] I was hoping to update what you put on the image (since you published it 2 years ago)
[2] Because I'd like to use your work in a project, but I'm a little concerned about using a black box as my docker image

Again, thanks for publishing this. I haven't found anything comparable on Github and I'm a bit disappointed you only have a couple stars/watchers on the project.

**Comment by birme** [comment]
Unfortunately I cannot find it either, but if I recall correctly it was a derivative of this image https://github.com/Eyevinn/docker-toolbelt

It is not optimal as it is a bit big and it is on my todo-list to build a more slim packager-base image.

**Comment by tecfu** [comment]
No problem, thanks for your help. Have you checked out [nytimes/nginx-vod-module](https://github.com/NYTimes/nginx-vod-module-docker)?
